import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type AppLanguage = "en" | "zh" | "id" | "ms";
export type AppTheme = "dark" | "light";

interface LanguageContextValue {
  language: AppLanguage;
  setLanguage: (language: AppLanguage) => void;
  theme: AppTheme;
  setTheme: (theme: AppTheme) => void;
  t: (key: string) => string;
  tx: (text?: string) => string;
}

const UI_TEXT: Record<AppLanguage, Record<string, string>> = {
  en: {
    language: "Language",
    english: "English",
    chinese: "中文",
    indonesia: "Indonesia",
    malay: "Melayu",
    darkMode: "Dark",
    lightMode: "Soft light",
    allSimulations: "All Simulations",
    exportReport: "Export Report",
    sampleData: "Sample data — run a simulation to generate a live report",
    riskSimulationPlatform: "Risk Simulation Platform",
    homeTitle: "FinGuard Twin AI",
    homeSubtitle: "Test fintech decisions against fraud, compliance, and operational risk — before they go live.",
    homeTagline: "Your next product decision has risk you haven't modelled yet.",
    runNewSimulation: "Run New Simulation",
    whatEngineAssesses: "What the engine assesses",
    recentSimulations: "Recent Simulations",
    viewAll: "View all",
    fraudVectorModelling: "Fraud Vector Modelling",
    fraudVectorModellingDesc: "Simulate how bad actors could exploit a new policy before it reaches production.",
    falsePositiveAnalysis: "False Positive Analysis",
    falsePositiveAnalysisDesc: "Identify which legitimate user segments would be blocked or degraded.",
    compliancePrecheck: "Compliance Pre-check",
    compliancePrecheckDesc: "Surface BNM, AML/CFT, and PDPA obligations triggered by the decision.",
    controlPlanGeneration: "Control Plan Generation",
    controlPlanGenerationDesc: "Receive actionable, prioritised controls with clear ownership.",
    newSimulation: "New Simulation",
    defineDecision: "Define the Decision",
    defineDecisionSubtitle: "Describe the fintech policy or product change you want to stress-test.",
    demoScenarios: "Demo scenarios",
    decisionDescription: "Decision Description",
    decisionPlaceholder: "Describe the specific policy, rule, or product change you want to simulate...",
    decisionHint: "Be specific — include current state, proposed state, and affected user segment if known.",
    decisionType: "Decision Type",
    companyType: "Company Type",
    selectType: "Select type...",
    marketContext: "Market / Regulatory Context",
    additionalContext: "Additional Context",
    optional: "optional",
    marketPlaceholder: "e.g. Malaysia, BNM-licensed e-wallet, Tier 2 KYC users only",
    additionalPlaceholder: "Business justification, constraints, or specific risk areas to focus on...",
    runRiskSimulation: "Run Risk Simulation",
    simulationHint: "Simulation completes in seconds. No API key required.",
    simulationFailed: "Simulation failed. Please try again.",
    buildingRiskSimulation: "Building risk simulation...",
    mappingFraudScenarios: "Mapping fraud scenarios...",
    estimatingFalsePositive: "Estimating false positive impact...",
    generatingControlPlan: "Generating control plan...",
    preparingSaferAlternative: "Preparing safer alternative...",
    riskAssessmentReport: "Risk Assessment Report",
    riskScore: "Risk Score (0–100)",
    displayScore: "Display score",
    criticalRisks: "Critical Risks",
    highRisks: "High Risks",
    controlsRecommended: "Controls Recommended",
    requireImmediateAction: "Require immediate action",
    requireControlPlan: "Require control plan",
    acrossAllRiskAreas: "Across all risk areas",
    finalRiskRating: "Final Risk Rating",
    decisionInput: "Decision Input",
    internalModelScore: "Internal model score",
    mainConcern: "Main Concern",
    launchRecommendation: "Launch Recommendation",
    affectedStakeholders: "Affected Stakeholders",
    riskMatrix: "Risk Matrix",
    detailedAnalysis: "Detailed Analysis",
    showDetailedAnalysis: "Show detailed analysis",
    hideDetailedAnalysis: "Hide detailed analysis",
    detailedAnalysisHint: "Open the supporting scenarios, compliance notes, controls, and safer alternative only when needed.",
    fraudAbuseScenarios: "Fraud Abuse Scenarios",
    fraudAbuseSub: "How a bad actor could exploit this decision if deployed as-is.",
    falsePositiveImpact: "False Positive Impact",
    falsePositiveSub: "Legitimate users who could be incorrectly blocked or degraded.",
    complianceConcerns: "Compliance Concerns",
    operationalRisks: "Operational Risks",
    reputationRisks: "Reputation Risks",
    recommendedControlPlan: "Recommended Control Plan",
    controlPlanSub: "Prioritised actions to bring this decision to an acceptable risk level.",
    saferAlternative: "Safer Alternative",
    likelihood: "Likelihood",
    impact: "Impact",
    veryHigh: "Very High",
    high: "High",
    medium: "Medium",
    low: "Low",
    critical: "Critical",
    assessmentFramework: "Assessment Framework",
    methodTitle: "How FinGuard Twin AI Works",
    methodSubtitle: "A structured, repeatable methodology for pre-launch risk assessment of fintech decisions.",
    sixRiskDimensions: "Six Risk Dimensions",
    sixRiskDimensionsDesc: "Every simulation assesses the proposed decision across six structured dimensions, producing a composite risk score and per-dimension analysis.",
    assessmentPipeline: "Assessment Pipeline",
    riskScoringModel: "Risk Scoring Model",
    internalScoreFormula: "Internal score formula",
    formulaText: "Internal Risk Score = Likelihood × Impact × Control Gap",
    formulaNote: "Each factor is scored from 1 to 5. Maximum internal score is 125. FinGuard Twin AI normalises this to a 0–100 display score for dashboard readability.",
    scopeLimitations: "Scope & Limitations",
    disclaimerText: "FinGuard Twin AI is a decision-support simulation tool. It does not process real customer financial data, does not make credit decisions, and does not replace legal, compliance, or professional risk review. Outputs are structured risk assessments intended to support — not replace — human compliance and fraud risk judgement. All simulations are based on the information provided and the engine's modelled risk patterns.",
    assessmentHistory: "Assessment History",
    pastSimulations: "Past Simulations",
    noSimulationsYet: "No simulations yet",
    noSimulationsDesc: "Run your first fintech decision risk assessment to generate a dashboard.",
    startNewSimulation: "Start New Simulation",
    newSimulationShort: "New Simulation",
    assessmentsInWorkspace: "assessment(s) in this workspace",
    decision: "Decision",
    date: "Date",
    riskRating: "Risk Rating",
  },
  zh: {
    language: "语言",
    english: "English",
    chinese: "中文",
    indonesia: "印尼语",
    malay: "马来语",
    darkMode: "深色",
    lightMode: "柔和浅色",
    allSimulations: "所有模拟",
    exportReport: "导出报告",
    sampleData: "示例数据 — 运行模拟后会生成真实报告",
    riskSimulationPlatform: "风险模拟平台",
    homeTitle: "FinGuard Twin AI",
    homeSubtitle: "在金融科技决策上线前，先测试欺诈、合规与运营风险。",
    homeTagline: "你的下一个产品决策，可能隐藏着还没被建模的风险。",
    runNewSimulation: "运行新模拟",
    whatEngineAssesses: "系统评估内容",
    recentSimulations: "最近模拟",
    viewAll: "查看全部",
    fraudVectorModelling: "欺诈路径建模",
    fraudVectorModellingDesc: "在政策上线前，模拟不良行为者可能如何利用漏洞。",
    falsePositiveAnalysis: "误伤分析",
    falsePositiveAnalysisDesc: "识别哪些真实用户可能被错误拦截、延迟或体验下降。",
    compliancePrecheck: "合规预检查",
    compliancePrecheckDesc: "识别该决策可能触发的 BNM、AML/CFT 与 PDPA 义务。",
    controlPlanGeneration: "控制方案生成",
    controlPlanGenerationDesc: "生成可执行、按优先级排序，并带有负责方的控制措施。",
    newSimulation: "新模拟",
    defineDecision: "定义决策",
    defineDecisionSubtitle: "描述你想压力测试的金融科技政策或产品变更。",
    demoScenarios: "演示场景",
    decisionDescription: "决策描述",
    decisionPlaceholder: "描述你想模拟的具体政策、规则或产品变更……",
    decisionHint: "请尽量具体，包括当前状态、拟议状态，以及受影响的用户群体。",
    decisionType: "决策类型",
    companyType: "公司类型",
    selectType: "选择类型……",
    marketContext: "市场 / 监管背景",
    additionalContext: "补充背景",
    optional: "可选",
    marketPlaceholder: "例如：马来西亚、BNM 持牌电子钱包、仅限 Tier 2 KYC 用户",
    additionalPlaceholder: "商业理由、限制条件，或希望重点关注的风险领域……",
    runRiskSimulation: "运行风险模拟",
    simulationHint: "模拟会在数秒内完成，不需要 API key。",
    simulationFailed: "模拟失败，请再试一次。",
    buildingRiskSimulation: "正在建立风险模拟……",
    mappingFraudScenarios: "正在映射欺诈场景……",
    estimatingFalsePositive: "正在估算误伤影响……",
    generatingControlPlan: "正在生成控制方案……",
    preparingSaferAlternative: "正在准备更安全替代方案……",
    riskAssessmentReport: "风险评估报告",
    riskScore: "风险分数（0–100）",
    displayScore: "展示分数",
    criticalRisks: "严重风险",
    highRisks: "高风险",
    controlsRecommended: "建议控制措施",
    requireImmediateAction: "需要立即处理",
    requireControlPlan: "需要控制方案",
    acrossAllRiskAreas: "覆盖所有风险领域",
    finalRiskRating: "最终风险等级",
    decisionInput: "决策输入",
    internalModelScore: "内部模型分数",
    mainConcern: "主要担忧",
    launchRecommendation: "上线建议",
    affectedStakeholders: "受影响相关方",
    riskMatrix: "风险矩阵",
    detailedAnalysis: "详细分析",
    showDetailedAnalysis: "显示详细分析",
    hideDetailedAnalysis: "收起详细分析",
    detailedAnalysisHint: "需要时再展开支持场景、合规说明、控制措施和替代方案。",
    fraudAbuseScenarios: "欺诈滥用场景",
    fraudAbuseSub: "如果照原方案上线，不良行为者可能如何利用该决策。",
    falsePositiveImpact: "误伤影响",
    falsePositiveSub: "可能被错误拦截或体验下降的真实用户。",
    complianceConcerns: "合规担忧",
    operationalRisks: "运营风险",
    reputationRisks: "声誉风险",
    recommendedControlPlan: "建议控制方案",
    controlPlanSub: "将该决策风险降至可接受水平的优先行动。",
    saferAlternative: "更安全替代方案",
    likelihood: "可能性",
    impact: "影响",
    veryHigh: "非常高",
    high: "高",
    medium: "中",
    low: "低",
    critical: "严重",
    assessmentFramework: "评估框架",
    methodTitle: "FinGuard Twin AI 如何运作",
    methodSubtitle: "用于金融科技决策上线前风险评估的结构化、可重复方法。",
    sixRiskDimensions: "六大风险维度",
    sixRiskDimensionsDesc: "每次模拟都会从六个结构化维度评估拟议决策，并生成综合风险分数与分维度分析。",
    assessmentPipeline: "评估流程",
    riskScoringModel: "风险评分模型",
    internalScoreFormula: "内部评分公式",
    formulaText: "内部风险分数 = 可能性 × 影响 × 控制缺口",
    formulaNote: "每个因子按 1 到 5 评分，最高内部得分为 125。FinGuard Twin AI 会将其标准化为 0–100 的展示分数，方便仪表盘阅读。",
    scopeLimitations: "范围与限制",
    disclaimerText: "FinGuard Twin AI 是决策支持模拟工具，不处理真实客户金融数据，不作出信贷决策，也不替代法律、合规或专业风险审查。输出内容是结构化风险评估，目的在于支持而不是取代人工合规与欺诈风险判断。所有模拟均基于用户提供的信息与系统建模的风险模式。",
    assessmentHistory: "评估历史",
    pastSimulations: "历史模拟",
    noSimulationsYet: "暂无模拟",
    noSimulationsDesc: "运行你的第一个金融科技决策风险评估，即可生成仪表盘。",
    startNewSimulation: "开始新模拟",
    newSimulationShort: "新模拟",
    assessmentsInWorkspace: "个工作区评估",
    decision: "决策",
    date: "日期",
    riskRating: "风险等级",
  },
  id: {
    language: "Bahasa",
    english: "Inggris",
    chinese: "Mandarin",
    indonesia: "Indonesia",
    malay: "Melayu",
    darkMode: "Gelap",
    lightMode: "Terang lembut",
    allSimulations: "Semua Simulasi",
    exportReport: "Ekspor Laporan",
    sampleData: "Data contoh — jalankan simulasi untuk membuat laporan langsung",
    riskSimulationPlatform: "Platform Simulasi Risiko",
    homeTitle: "FinGuard Twin AI",
    homeSubtitle: "Uji keputusan fintech terhadap risiko fraud, kepatuhan, dan operasional sebelum diluncurkan.",
    homeTagline: "Keputusan produk berikutnya mungkin memiliki risiko yang belum dimodelkan.",
    runNewSimulation: "Jalankan Simulasi Baru",
    whatEngineAssesses: "Yang dinilai oleh mesin",
    recentSimulations: "Simulasi Terbaru",
    viewAll: "Lihat semua",
    fraudVectorModelling: "Pemodelan Vektor Fraud",
    fraudVectorModellingDesc: "Simulasikan bagaimana pelaku buruk dapat mengeksploitasi kebijakan baru sebelum masuk produksi.",
    falsePositiveAnalysis: "Analisis False Positive",
    falsePositiveAnalysisDesc: "Identifikasi segmen pengguna sah yang dapat terblokir atau terganggu.",
    compliancePrecheck: "Pra-pemeriksaan Kepatuhan",
    compliancePrecheckDesc: "Tampilkan kewajiban BNM, AML/CFT, dan PDPA yang dipicu oleh keputusan.",
    controlPlanGeneration: "Pembuatan Rencana Kontrol",
    controlPlanGenerationDesc: "Dapatkan kontrol yang dapat ditindaklanjuti, diprioritaskan, dan memiliki pemilik yang jelas.",
    newSimulation: "Simulasi Baru",
    defineDecision: "Definisikan Keputusan",
    defineDecisionSubtitle: "Jelaskan kebijakan fintech atau perubahan produk yang ingin diuji tekanannya.",
    demoScenarios: "Skenario demo",
    decisionDescription: "Deskripsi Keputusan",
    decisionPlaceholder: "Jelaskan kebijakan, aturan, atau perubahan produk yang ingin disimulasikan...",
    decisionHint: "Tulis secara spesifik — sertakan kondisi saat ini, usulan perubahan, dan segmen pengguna terdampak jika diketahui.",
    decisionType: "Jenis Keputusan",
    companyType: "Jenis Perusahaan",
    selectType: "Pilih jenis...",
    marketContext: "Konteks Pasar / Regulasi",
    additionalContext: "Konteks Tambahan",
    optional: "opsional",
    marketPlaceholder: "mis. Malaysia, e-wallet berlisensi BNM, hanya pengguna Tier 2 KYC",
    additionalPlaceholder: "Alasan bisnis, batasan, atau area risiko tertentu yang perlu difokuskan...",
    runRiskSimulation: "Jalankan Simulasi Risiko",
    simulationHint: "Simulasi selesai dalam hitungan detik. Tidak perlu API key.",
    simulationFailed: "Simulasi gagal. Silakan coba lagi.",
    buildingRiskSimulation: "Membangun simulasi risiko...",
    mappingFraudScenarios: "Memetakan skenario fraud...",
    estimatingFalsePositive: "Mengestimasi dampak false positive...",
    generatingControlPlan: "Membuat rencana kontrol...",
    preparingSaferAlternative: "Menyiapkan alternatif yang lebih aman...",
    riskAssessmentReport: "Laporan Penilaian Risiko",
    riskScore: "Skor Risiko (0–100)",
    displayScore: "Skor tampilan",
    criticalRisks: "Risiko Kritis",
    highRisks: "Risiko Tinggi",
    controlsRecommended: "Kontrol Direkomendasikan",
    requireImmediateAction: "Perlu tindakan segera",
    requireControlPlan: "Perlu rencana kontrol",
    acrossAllRiskAreas: "Di semua area risiko",
    finalRiskRating: "Peringkat Risiko Akhir",
    decisionInput: "Input Keputusan",
    internalModelScore: "Skor model internal",
    mainConcern: "Kekhawatiran Utama",
    launchRecommendation: "Rekomendasi Peluncuran",
    affectedStakeholders: "Pemangku Kepentingan Terdampak",
    riskMatrix: "Matriks Risiko",
    detailedAnalysis: "Analisis Detail",
    showDetailedAnalysis: "Tampilkan analisis detail",
    hideDetailedAnalysis: "Sembunyikan analisis detail",
    detailedAnalysisHint: "Buka skenario pendukung, catatan kepatuhan, kontrol, dan alternatif hanya saat diperlukan.",
    fraudAbuseScenarios: "Skenario Penyalahgunaan Fraud",
    fraudAbuseSub: "Bagaimana pelaku buruk dapat mengeksploitasi keputusan ini bila diluncurkan apa adanya.",
    falsePositiveImpact: "Dampak False Positive",
    falsePositiveSub: "Pengguna sah yang dapat salah diblokir atau mengalami penurunan layanan.",
    complianceConcerns: "Kekhawatiran Kepatuhan",
    operationalRisks: "Risiko Operasional",
    reputationRisks: "Risiko Reputasi",
    recommendedControlPlan: "Rencana Kontrol Direkomendasikan",
    controlPlanSub: "Tindakan prioritas untuk menurunkan keputusan ini ke tingkat risiko yang dapat diterima.",
    saferAlternative: "Alternatif Lebih Aman",
    likelihood: "Kemungkinan",
    impact: "Dampak",
    veryHigh: "Sangat Tinggi",
    high: "Tinggi",
    medium: "Sedang",
    low: "Rendah",
    critical: "Kritis",
    assessmentFramework: "Kerangka Penilaian",
    methodTitle: "Cara Kerja FinGuard Twin AI",
    methodSubtitle: "Metodologi terstruktur dan berulang untuk penilaian risiko keputusan fintech sebelum peluncuran.",
    sixRiskDimensions: "Enam Dimensi Risiko",
    sixRiskDimensionsDesc: "Setiap simulasi menilai keputusan yang diusulkan dalam enam dimensi terstruktur dan menghasilkan skor risiko komposit serta analisis per dimensi.",
    assessmentPipeline: "Alur Penilaian",
    riskScoringModel: "Model Skoring Risiko",
    internalScoreFormula: "Formula skor internal",
    formulaText: "Skor Risiko Internal = Kemungkinan × Dampak × Kesenjangan Kontrol",
    formulaNote: "Setiap faktor diberi skor 1 sampai 5. Skor internal maksimum adalah 125. FinGuard Twin AI menormalkan skor ini menjadi 0–100 agar dashboard lebih mudah dibaca.",
    scopeLimitations: "Ruang Lingkup & Batasan",
    disclaimerText: "FinGuard Twin AI adalah alat simulasi pendukung keputusan. Alat ini tidak memproses data keuangan pelanggan nyata, tidak membuat keputusan kredit, dan tidak menggantikan tinjauan legal, kepatuhan, atau risiko profesional. Output berupa penilaian risiko terstruktur untuk mendukung — bukan menggantikan — penilaian manusia dalam kepatuhan dan risiko fraud.",
    assessmentHistory: "Riwayat Penilaian",
    pastSimulations: "Simulasi Sebelumnya",
    noSimulationsYet: "Belum ada simulasi",
    noSimulationsDesc: "Jalankan penilaian risiko keputusan fintech pertama untuk membuat dashboard.",
    startNewSimulation: "Mulai Simulasi Baru",
    newSimulationShort: "Simulasi Baru",
    assessmentsInWorkspace: "penilaian di workspace ini",
    decision: "Keputusan",
    date: "Tanggal",
    riskRating: "Peringkat Risiko",
  },
  ms: {
    language: "Bahasa",
    english: "Inggeris",
    chinese: "Cina",
    indonesia: "Indonesia",
    malay: "Melayu",
    darkMode: "Gelap",
    lightMode: "Cerah lembut",
    allSimulations: "Semua Simulasi",
    exportReport: "Eksport Laporan",
    sampleData: "Data contoh — jalankan simulasi untuk menjana laporan sebenar",
    riskSimulationPlatform: "Platform Simulasi Risiko",
    homeTitle: "FinGuard Twin AI",
    homeSubtitle: "Uji keputusan fintech terhadap risiko penipuan, pematuhan dan operasi sebelum dilancarkan.",
    homeTagline: "Keputusan produk seterusnya mungkin mempunyai risiko yang belum dimodelkan.",
    runNewSimulation: "Jalankan Simulasi Baharu",
    whatEngineAssesses: "Apa yang dinilai oleh enjin",
    recentSimulations: "Simulasi Terkini",
    viewAll: "Lihat semua",
    fraudVectorModelling: "Pemodelan Vektor Penipuan",
    fraudVectorModellingDesc: "Simulasikan bagaimana pelaku berniat jahat boleh mengeksploitasi polisi baharu sebelum ia dilancarkan.",
    falsePositiveAnalysis: "Analisis Positif Palsu",
    falsePositiveAnalysisDesc: "Kenal pasti segmen pengguna sah yang mungkin disekat atau terjejas.",
    compliancePrecheck: "Semakan Awal Pematuhan",
    compliancePrecheckDesc: "Paparkan kewajipan BNM, AML/CFT dan PDPA yang dicetuskan oleh keputusan.",
    controlPlanGeneration: "Penjanaan Pelan Kawalan",
    controlPlanGenerationDesc: "Terima kawalan yang boleh dilaksanakan, mengikut keutamaan dan pemilik yang jelas.",
    newSimulation: "Simulasi Baharu",
    defineDecision: "Takrifkan Keputusan",
    defineDecisionSubtitle: "Terangkan polisi fintech atau perubahan produk yang ingin diuji tekanannya.",
    demoScenarios: "Senario demo",
    decisionDescription: "Huraian Keputusan",
    decisionPlaceholder: "Terangkan polisi, peraturan atau perubahan produk yang ingin disimulasikan...",
    decisionHint: "Nyatakan dengan khusus — sertakan keadaan semasa, keadaan dicadangkan dan segmen pengguna terkesan jika diketahui.",
    decisionType: "Jenis Keputusan",
    companyType: "Jenis Syarikat",
    selectType: "Pilih jenis...",
    marketContext: "Konteks Pasaran / Peraturan",
    additionalContext: "Konteks Tambahan",
    optional: "pilihan",
    marketPlaceholder: "cth. Malaysia, e-dompet berlesen BNM, pengguna Tier 2 KYC sahaja",
    additionalPlaceholder: "Justifikasi bisnes, kekangan, atau area risiko khusus untuk difokuskan...",
    runRiskSimulation: "Jalankan Simulasi Risiko",
    simulationHint: "Simulasi selesai dalam beberapa saat. API key tidak diperlukan.",
    simulationFailed: "Simulasi gagal. Sila cuba lagi.",
    buildingRiskSimulation: "Membina simulasi risiko...",
    mappingFraudScenarios: "Memetakan senario penipuan...",
    estimatingFalsePositive: "Menganggar impak positif palsu...",
    generatingControlPlan: "Menjana pelan kawalan...",
    preparingSaferAlternative: "Menyediakan alternatif yang lebih selamat...",
    riskAssessmentReport: "Laporan Penilaian Risiko",
    riskScore: "Skor Risiko (0–100)",
    displayScore: "Skor paparan",
    criticalRisks: "Risiko Kritikal",
    highRisks: "Risiko Tinggi",
    controlsRecommended: "Kawalan Dicadangkan",
    requireImmediateAction: "Perlu tindakan segera",
    requireControlPlan: "Perlu pelan kawalan",
    acrossAllRiskAreas: "Di semua area risiko",
    finalRiskRating: "Penarafan Risiko Akhir",
    decisionInput: "Input Keputusan",
    internalModelScore: "Skor model dalaman",
    mainConcern: "Kebimbangan Utama",
    launchRecommendation: "Cadangan Pelancaran",
    affectedStakeholders: "Pihak Berkepentingan Terkesan",
    riskMatrix: "Matriks Risiko",
    detailedAnalysis: "Analisis Terperinci",
    showDetailedAnalysis: "Tunjuk analisis terperinci",
    hideDetailedAnalysis: "Sembunyikan analisis terperinci",
    detailedAnalysisHint: "Buka senario sokongan, nota pematuhan, kawalan dan alternatif hanya bila diperlukan.",
    fraudAbuseScenarios: "Senario Penyalahgunaan Penipuan",
    fraudAbuseSub: "Bagaimana pelaku berniat jahat boleh mengeksploitasi keputusan ini jika dilancarkan seadanya.",
    falsePositiveImpact: "Impak Positif Palsu",
    falsePositiveSub: "Pengguna sah yang mungkin tersalah sekat atau mengalami penurunan servis.",
    complianceConcerns: "Kebimbangan Pematuhan",
    operationalRisks: "Risiko Operasi",
    reputationRisks: "Risiko Reputasi",
    recommendedControlPlan: "Pelan Kawalan Dicadangkan",
    controlPlanSub: "Tindakan keutamaan untuk membawa keputusan ini ke tahap risiko yang boleh diterima.",
    saferAlternative: "Alternatif Lebih Selamat",
    likelihood: "Kemungkinan",
    impact: "Impak",
    veryHigh: "Sangat Tinggi",
    high: "Tinggi",
    medium: "Sederhana",
    low: "Rendah",
    critical: "Kritikal",
    assessmentFramework: "Rangka Kerja Penilaian",
    methodTitle: "Cara FinGuard Twin AI Berfungsi",
    methodSubtitle: "Metodologi berstruktur dan berulang untuk penilaian risiko keputusan fintech sebelum pelancaran.",
    sixRiskDimensions: "Enam Dimensi Risiko",
    sixRiskDimensionsDesc: "Setiap simulasi menilai keputusan dicadangkan merentas enam dimensi berstruktur dan menghasilkan skor risiko komposit serta analisis setiap dimensi.",
    assessmentPipeline: "Aliran Penilaian",
    riskScoringModel: "Model Skor Risiko",
    internalScoreFormula: "Formula skor dalaman",
    formulaText: "Skor Risiko Dalaman = Kemungkinan × Impak × Jurang Kawalan",
    formulaNote: "Setiap faktor diberi skor 1 hingga 5. Skor dalaman maksimum ialah 125. FinGuard Twin AI menormalkan skor ini kepada 0–100 untuk memudahkan bacaan dashboard.",
    scopeLimitations: "Skop & Had",
    disclaimerText: "FinGuard Twin AI ialah alat simulasi sokongan keputusan. Ia tidak memproses data kewangan pelanggan sebenar, tidak membuat keputusan kredit dan tidak menggantikan semakan undang-undang, pematuhan atau risiko profesional. Output ialah penilaian risiko berstruktur untuk menyokong — bukan menggantikan — pertimbangan manusia dalam pematuhan dan risiko penipuan.",
    assessmentHistory: "Sejarah Penilaian",
    pastSimulations: "Simulasi Lepas",
    noSimulationsYet: "Belum ada simulasi",
    noSimulationsDesc: "Jalankan penilaian risiko keputusan fintech pertama untuk menjana dashboard.",
    startNewSimulation: "Mula Simulasi Baharu",
    newSimulationShort: "Simulasi Baharu",
    assessmentsInWorkspace: "penilaian dalam workspace ini",
    decision: "Keputusan",
    date: "Tarikh",
    riskRating: "Penarafan Risiko",
  },
};

const PHRASE_TRANSLATIONS: Record<AppLanguage, Record<string, string>> = {
  en: {},
  zh: {
    "Launch with mitigation": "在缓解措施下上线",
    "Do not launch": "不要上线",
    "Proceed with monitoring": "在监控下继续",
    "Gemini AI": "Gemini AI",
    "Fallback Engine": "备用引擎",
    "Fraud Risk": "欺诈风险",
    "Compliance Risk": "合规风险",
    "False Positive Risk": "误伤风险",
    "User Harm Risk": "用户伤害风险",
    "Operational Risk": "运营风险",
    "Reputation Risk": "声誉风险",
  },
  id: {
    "Launch with mitigation": "Luncurkan dengan mitigasi",
    "Do not launch": "Jangan diluncurkan",
    "Proceed with monitoring": "Lanjutkan dengan pemantauan",
    "Gemini AI": "Gemini AI",
    "Fallback Engine": "Mesin Cadangan",
    "Fraud Risk": "Risiko Fraud",
    "Compliance Risk": "Risiko Kepatuhan",
    "False Positive Risk": "Risiko False Positive",
    "User Harm Risk": "Risiko Kerugian Pengguna",
    "Operational Risk": "Risiko Operasional",
    "Reputation Risk": "Risiko Reputasi",
  },
  ms: {
    "Launch with mitigation": "Lancar dengan mitigasi",
    "Do not launch": "Jangan lancarkan",
    "Proceed with monitoring": "Teruskan dengan pemantauan",
    "Gemini AI": "Gemini AI",
    "Fallback Engine": "Enjin Sandaran",
    "Fraud Risk": "Risiko Penipuan",
    "Compliance Risk": "Risiko Pematuhan",
    "False Positive Risk": "Risiko Positif Palsu",
    "User Harm Risk": "Risiko Mudarat Pengguna",
    "Operational Risk": "Risiko Operasi",
    "Reputation Risk": "Risiko Reputasi",
  },
};

function replaceCommonTerms(text: string, language: AppLanguage) {
  if (language === "en") return text;
  const terms = PHRASE_TRANSLATIONS[language];
  let output = text;
  Object.entries(terms).forEach(([from, to]) => {
    output = output.split(from).join(to);
  });
  return output;
}

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<AppLanguage>(() => {
    const saved = localStorage.getItem("finguard-language") as AppLanguage | null;
    return saved === "zh" || saved === "id" || saved === "ms" || saved === "en" ? saved : "en";
  });

  const [theme, setThemeState] = useState<AppTheme>(() => {
    const saved = localStorage.getItem("finguard-theme") as AppTheme | null;
    return saved === "light" || saved === "dark" ? saved : "dark";
  });

  useEffect(() => {
    localStorage.setItem("finguard-language", language);
    document.documentElement.lang = language === "zh" ? "zh-CN" : language === "ms" ? "ms-MY" : language === "id" ? "id-ID" : "en";
  }, [language]);

  useEffect(() => {
    localStorage.setItem("finguard-theme", theme);
    document.documentElement.dataset.theme = theme;
  }, [theme]);

  const value = useMemo<LanguageContextValue>(() => ({
    language,
    setLanguage: setLanguageState,
    theme,
    setTheme: setThemeState,
    t: (key: string) => UI_TEXT[language][key] ?? UI_TEXT.en[key] ?? key,
    tx: (text?: string) => {
      if (!text) return "";
      const exact = PHRASE_TRANSLATIONS[language][text];
      return exact ?? replaceCommonTerms(text, language);
    },
  }), [language, theme]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used inside LanguageProvider");
  }
  return context;
}
